name: Update advantagescope AUR package

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_version:
    runs-on: ubuntu-latest
    outputs:
      need_update: ${{ steps.check_version.outputs.need_update }}
      latest_version: ${{ steps.check_version.outputs.latest_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup up Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Check if update is needed
        id: check_version
        run: |
          cd advantagescope
          LATEST_VERSION=$(curl -s -o /dev/null -w "%{redirect_url}\n" https://github.com/Mechanical-Advantage/AdvantageScope/releases/latest | sed 's|.*/tag/v\?||')
          echo "Latest version is $LATEST_VERSION"
           CURRENT_VERSION=$(grep -oP '(?<=pkgver=)[0-9.]+' PKGBUILD)
           echo "Current version is $CURRENT_VERSION"
          # Determine if an update is needed
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "need_update=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_update=false" >> "$GITHUB_OUTPUT"
          fi

          # Save the version information for later steps
          echo "latest_version=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
          echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Update PKGBUILD
        if: steps.check_version.outputs.need_update == 'true'
        run: |
          LATEST_VERSION=${{ steps.check_version.outputs.latest_version }}
          cd advantagescope
          sed -i "s/pkgver=.*/pkgver=$LATEST_VERSION/" PKGBUILD
          sed -i "s/pkgver=.*/pkgver=$LATEST_VERSION/" .SRCINFO
          git add PKGBUILD .SRCINFO
          git commit -m "Update mbed-studio-bin to version $LATEST_VERSION"
          git push
